Kontener z modelem i API (7)
Kolo-Naukowe-Data-Science-PW/mlops-project pull request #11
Opened 2022-11-12 22:07 UTC by AdamixD

2022-11-13 12:24 UTC, HermanPlay commented on containerized_ml_models/model_api_7/app.py
> +    model = pickle.load(open('model.pkl', 'rb'))
In line 18, I am afraid you do not close the file, it can cause some issues. Wouldn't it be better to close it before return?

2022-11-13 12:25 UTC, HermanPlay requested changes
Everything is good, except one thing, which I think should be changed.

2022-11-13 12:28 UTC, HermanPlay requested changes
Everything is good, except one thing, which I think should be changed. Should also, fix docker file.

2022-11-13 12:28 UTC, HermanPlay commented on containerized_ml_models/model_api_7/Dockerfile
> +ENTRYPOINT [ "conda", "run", "-n", "env" ,"--no-capture-output", "python", "app.py"]
You should consider adding new line at the end od the file.
Explanation: https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

2022-11-14 15:43 UTC, HermanPlay commented
Also run black app on your python file, to fix lint problems.

2022-11-17 18:49 UTC, matined approved these changes

2022-11-17 18:49 UTC, matined commented
Please, resolve all comments. We'll merge it after

2022-11-28 10:44 UTC, HermanPlay approved these changes
LGTM

2022-11-30 22:25 UTC, merged