Container with api to model 1
Kolo-Naukowe-Data-Science-PW/mlops-project pull request #13
Opened 2022-11-13 10:29 UTC by MattS0000

2022-11-13 15:58 UTC, matined commented
Please change the base branch to 'develop' ;)

2022-11-15 17:38 UTC, KubaKrzych requested changes
Nie ma co zostawiać obsługi nieodpowiedniego formatu w ten sposób, bo i tak to nie ma znaczenia dla api. 

Równie dobrze można rzucić requesta z danymi: "abc" i dostaniemy ten sam error, co podając:[[1,2.65,3,4,5,6.124,7,8,9,10], [1,2,67,4,5,7.065,7,1,9]] 
(druga lista ma o jeden element za mało -> raise ValueError)

2022-11-15 17:38 UTC, KubaKrzych commented on containerized_ml_models/model_1/api.py
> +        )
To i tak nie ma znaczenia dla działania api, bo jeśli strzelisz do api requestem, który nie ma odpowiedniego formatu / nie jest przygotowane api pod niego, to dostaniesz i tak Internal Server Error.

src:
https://flask.palletsprojects.com/en/2.2.x/errorhandling/

2022-11-16 16:17 UTC, KubaKrzych approved these changes

2022-11-18 15:59 UTC, merged